name: sig_db_services_immobiliers
description: Application SIG mobile
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.1.0
  geolocator: ^10.0.0
  flutter_map_tile_caching: ^9.0.0
